=== AdriPortAtil/La-elite/Videojuegos.dtd
<!ELEMENT VIDEOJUEGOS (videojuego)+>
<!ELEMENT videojuego (titulo, genero, dificultad, breve_descripcion, )>
	<!ELEMENT titulo (#PCDATA)>
	<!ELEMENT genero (#PCDATA)>
	<!ELEMENT dificultad (#PCDATA)>
	<!ELEMENT breve_descripcion (#PCDATA)>
	<!ELEMENT desarrolladores (desarrolllador+)>
		<!ELEMENT desarrollador (#PCDATA)>
		<!ATTLIST pais_de_origen CDATA #IMPLIED>

=== AdriPortAtil/La-elite/Videojuegos.xml
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet href="estilos/Videojuegos.css"?>
<!DOCTYPE RECETAS SYSTEM "Videojuegos.dtd">

<VIDEOJUEGOS>
	<videojuego>
		<titulo></titulo>
		<genero></genero>
		<dificultad></dificultad>
		<breve_descripcion></breve_descripcion>
		<desarrolladores>
			<desarrollador></desarrollador>
				<pais_de_origen></pais_de_origen>
			<desarrollador></desarrollador>
				<pais_de_origen></pais_de_origen>
		</desarrolladores>
	</videojuego>
</VIDEOJUEGOS>
